# Generated by Django 3.1.4 on 2021-01-07 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0002_auto_20210106_1817'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='phone',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
